const products = [
  {
    id: "1",
    name: "花帕",
    image: "",
    description: "",
    category: "",
    price: 15,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "2",
    name: "缘钱",
    image: "",
    description: "一包",
    category: "",
    price: 5,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "3",
    name: "春花",
    image: "",
    description: "一对",
    category: "",
    price: 2,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "4",
    name: "新娘伞",
    image: "",
    description: "",
    category: "",
    price: 39,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "5",
    name: "针线盒/梳子/镜子",
    image: "",
    description: "三样一套",
    category: "",
    price: 55,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "6",
    name: "聘金盒",
    image: "",
    description: "一个",
    category: "",
    price: 139,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "7",
    name: "毛巾",
    image: "",
    description: "两条",
    category: "",
    price: 39,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "8",
    name: "浴巾",
    image: "",
    description: "一条",
    category: "",
    price: 69,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "9",
    name: "盖杯带盘",
    image: "",
    description: "一套",
    category: "",
    price: 88,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "10",
    name: "脸盆/脚盆",
    image: "",
    description: "1对",
    category: "",
    price: 22,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "11",
    name: "对碗",
    image: "",
    description: "6件套",
    category: "",
    price: 39,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "12",
    name: "糖缸",
    image: "",
    description: "一对",
    category: "",
    price: 58,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "13",
    name: "长明灯",
    image: "",
    description: "一对",
    category: "",
    price: 39,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "14",
    name: "中堂母舅联",
    image: "",
    description: "一副",
    category: "",
    price: 78,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "15",
    name: "糖果袋",
    image: "",
    description: "大号",
    category: "",
    price: 4,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "16",
    name: "糖果袋",
    image: "",
    description: "中号",
    category: "",
    price: 3,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "17",
    name: "糖果袋",
    image: "",
    description: "小号",
    category: "",
    price: 2,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "18",
    name: "",
    image: "",
    description: "手抛喜一包30个",
    category: "",
    price: 6,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "19",
    name: "带遥控的电子鞭炮",
    image: "",
    description: "一盒",
    category: "",
    price: 129,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "20",
    name: "龙凤蜡烛",
    image: "",
    description: "一对",
    category: "",
    price: 80,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "21",
    name: "压床娃娃",
    image: "",
    description: "一对",
    category: "",
    price: 108,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "22",
    name: "船灯",
    image: "",
    description: "一对",
    category: "",
    price: 39,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "23",
    name: "龙凤拖鞋",
    image: "",
    description: "2双",
    category: "",
    price: 158,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "24",
    name: "红提篮",
    image: "",
    description: "",
    category: "",
    price: 78,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "25",
    name: "婚床摆件",
    image: "",
    description: "一套",
    category: "",
    price: 29,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "26",
    name: "敬茶跪垫",
    image: "",
    description: "一对",
    category: "",
    price: 59,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "27",
    name: "礼花",
    image: "",
    description: "一支",
    category: "",
    price: 10,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "28",
    name: "喜字",
    image: "",
    description: "50公分/一张",
    category: "",
    price: 9.9,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "29",
    name: "金箔纸碗",
    image: "",
    description: "一包20个",
    category: "",
    price: 18,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "30",
    name: "纸杯/",
    image: "",
    description: "一包20个",
    category: "",
    price: 10,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "31",
    name: "汤勺",
    image: "",
    description: "20个",
    category: "",
    price: 10,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "32",
    name: "送日子书（订婚书）",
    image: "",
    description: "一套",
    category: "",
    price: 68,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "33",
    name: "胸花",
    image: "",
    description: "一对",
    category: "",
    price: 28,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "34",
    name: "对娃摆件",
    image: "",
    description: "一对",
    category: "",
    price: 68,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "35",
    name: "万元红包",
    image: "",
    description: "一包6个",
    category: "",
    price: 12,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "36",
    name: "千元红包",
    image: "",
    description: "一包6个",
    category: "",
    price: 5,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "37",
    name: "百元红包",
    image: "",
    description: "一包6个",
    category: "",
    price: 3,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "38",
    name: "婚房喜字摆件",
    image: "",
    description: "一对",
    category: "",
    price: 39,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "39",
    name: "石榴红气球",
    image: "",
    description: "一包",
    category: "",
    price: 49,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "40",
    name: "喜庆纸巾",
    image: "",
    description: "一包",
    category: "",
    price: 2.5,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "41",
    name: "婚庆自粘布绒对联",
    image: "",
    description: "1.1m",
    category: "",
    price: 25,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "42",
    name: "婚庆自粘布绒对联",
    image: "",
    description: "1.3m",
    category: "",
    price: 30,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "43",
    name: "婚庆自粘布绒对联",
    image: "",
    description: "1.6m",
    category: "",
    price: 35,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "44",
    name: "婚庆拖鞋",
    image: "",
    description: "一对",
    category: "",
    price: 78,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "45",
    name: "毛毡礼袋",
    image: "",
    description: "1个",
    category: "",
    price: 25,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "46",
    name: "喜字拉花",
    image: "",
    description: "1条",
    category: "",
    price: 15,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "47",
    name: "团扇",
    image: "",
    description: "1个",
    category: "",
    price: 68,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "48",
    name: "手巾扇",
    image: "",
    description: "一套",
    category: "",
    price: 16,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "49",
    name: "304材质热水瓶",
    image: "",
    description: "一个",
    category: "",
    price: 78,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "50",
    name: "喜庆茶壶",
    image: "",
    description: "一个",
    category: "",
    price: 58,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    id: "51",
    name: "走马灯",
    image: "",
    description: "一个",
    category: "",
    price: 139,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
];
